# Generated by Django 3.2.11 on 2023-08-08 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_post', '0002_auto_20230808_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
